// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1GFTXXsy8bTFOajhiObnAVEGu469bQ4A',
    appId: '1:470598591038:web:c0e766ecd9ff42f886e76f',
    messagingSenderId: '470598591038',
    projectId: 'noborresnada',
    authDomain: 'noborresnada.firebaseapp.com',
    storageBucket: 'noborresnada.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA37stg4WFvysTutPdX9c8bAQcqo4jynHQ',
    appId: '1:470598591038:android:0a69994ef7fede4386e76f',
    messagingSenderId: '470598591038',
    projectId: 'noborresnada',
    storageBucket: 'noborresnada.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_I1m3J3Io0Ew3rT9GwYIaUPjGzfHeERw',
    appId: '1:470598591038:ios:20bac20007e79ca286e76f',
    messagingSenderId: '470598591038',
    projectId: 'noborresnada',
    storageBucket: 'noborresnada.appspot.com',
    androidClientId: '470598591038-k4pvlfe75kiussgc19vgb22v5odd5c62.apps.googleusercontent.com',
    iosClientId: '470598591038-57sto86qeeqskpvjpun4pk9587pfv0uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_I1m3J3Io0Ew3rT9GwYIaUPjGzfHeERw',
    appId: '1:470598591038:ios:20bac20007e79ca286e76f',
    messagingSenderId: '470598591038',
    projectId: 'noborresnada',
    storageBucket: 'noborresnada.appspot.com',
    androidClientId: '470598591038-k4pvlfe75kiussgc19vgb22v5odd5c62.apps.googleusercontent.com',
    iosClientId: '470598591038-57sto86qeeqskpvjpun4pk9587pfv0uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
